### PR TITLE
Fix auto layout size calculation

### LINKED ISSUE #36: AutoLayout Not Working Correctly with ActiveLabel
I'm using ActiveLabel as the Custom Class for my post’s content labels in the Storyboard; however, I believe it is interfering with Autolayout. For some reason the post’s content gets cut off (screenshot attached).

I guess it’s hard to know without seeing my code - but do you have a clue why this might be? 

img_1008

### LINKED ISSUE #45: AutoLayout and custom font
This was mentioned in a another issue but my problem is specific to font.

When I use a custom font, PTSans, the text is cut off at the end. 

**this is what it should look like:**

screen shot 2016-02-11 at 12 43 02 pm

**And this is what it looks with with ActiveLabel**

screen shot 2016-02-11 at 12 43 58 pm

**Notice the text and time stamp at the end is missing**

This is a label inside a tableview cell using Automatic dimensions for the height. the cell height changes based on the size of the label.

### PR DESCRIPTION
**Pull request by Econa77**
Size calculation of AutoLayout has shifted to when using the ActiveLabel of customized state in the Storyboard.
So it has been changed to return the correct size using the `layoutManager`

**Before**

**After**

## Fix
- Fixes #36 
- Fixes #45 
- Fixes #67

## Check
- Check if not destroy the existing implementation and performance
 - [x] To use the ActiveLabel in code base (AutoSizing)
 - [x] To use the ActiveLabel in code base (AutoLayout)
 - [x] To use the ActiveLabel in Storyboard base (AutoSizing)
 - [x] To use the ActiveLabel in Storyboard base (AutoLayout)
 - [x] Use custom fonts

### CODE REVIEW

**Comment by ndbroadbent** [comment]
Thanks, this is great! Now I just need to figure out how to respect `numberOfLines` and properly truncate the text.

File: ActiveLabel/ActiveLabel.swift [hunk 1]
```diff
@@ -130,6 +130,14 @@ public protocol ActiveLabelDelegate: class {
         return self
     }
 
+    // MARK: - Auto layout
+    public override func intrinsicContentSize() -> CGSize {
+        let superSize = super.intrinsicContentSize()
+        textContainer.size = CGSize(width: superSize.width, height: CGFloat.max)
+        let size = layoutManager.usedRectForTextContainer(textContainer)
+        return CGSize(width: size.width, height: ceil(size.height))
```
Comment (Econa77) [inline ActiveLabel/ActiveLabel.swift]: When `numberOfLine` is 0 in this calculation, the normal UILabel has confirmed the same size.

**Comment by Econa77** [comment]
@poolqf Please review code 🙏

File: ActiveLabel/ActiveLabel.swift [hunk 2]
```diff
@@ -130,6 +130,14 @@ public protocol ActiveLabelDelegate: class {
         return self
     }
 
+    // MARK: - Auto layout
+    public override func intrinsicContentSize() -> CGSize {
+        let superSize = super.intrinsicContentSize()
+        textContainer.size = CGSize(width: superSize.width, height: CGFloat.max)
```
Comment (poolqf) [inline ActiveLabel/ActiveLabel.swift]: HI @Econa77, I am not sure about changing the textContainer size and not revert it...

Comment (Econa77) [inline ActiveLabel/ActiveLabel.swift]: The reason I changed the size of `textContainer` is as follows.

#### If don't change the size, It don't fit the calculation of height 

Calculation of height will be calculated as the upper limit of the height that has been set on the Storyboard.





By changing the size of `textContainer`, ActiveLabel can always returns the correct value.


The reason I have not reverted size is always changed current label size in drawTextInRect.
https://github.com/optonaut/ActiveLabel.swift/blob/master/ActiveLabel/ActiveLabel.swift#L116

Comment (poolqf) [inline ActiveLabel/ActiveLabel.swift]: Hi @Econa77, thanks for the explanation. Just one last thing before merging.

Is drawTextInRect always executed after instrinsicContentSize?

Comment (Econa77) [inline ActiveLabel/ActiveLabel.swift]: @poolqf 
Yes, it has been executed after `instrinsicContentSize`.
